### ISSUE TITLE
Queue doesn't process in order?

### ISSUE THREAD

**Issue by PaulWieland** [charto/cwait#11]
I wrote this simple program to test `cwait`:

```javascript
var cwait = require('cwait');

function asyncLog(x,y){
	return(new Promise(function(resolve, reject) {
		setTimeout(function(){
			console.log(x,y);
			resolve();
		},100)
	}));
}

var queue = new cwait.TaskQueue(Promise, 1);

[1,2,3,4,5].forEach((el) => {
	console.log(el);
	queue.wrap(asyncLog)("q:",el);
})
```

I expected it to output :

```
1
2
3
4
5
q: 1
q: 2
q: 3
q: 4
q: 5
```

But instead it outputs: 

```
1
2
3
4
5
q: 1
q: 2
q: 5
q: 4
q: 3
```

EDIT: After testing repeatedly, it does output the array in order _sometimes_. Now I am even more confused.

**Comment by jjrv** [comment]
It uses a binary heap to maintain a priority queue, for supporting a delay before scheduling a task. If multiple tasks are queued to start at the same time, the priority queue doesn't try to maintain their order.

If you need things to run in a specific order, you should chain the promises, exactly as when not using cwait.
