### ISSUE TITLE
Add task to empty queue

### ISSUE THREAD

**Issue by paglias** [charto/cwait#4]
Hi,

It's possible to add a task to the queue after it's been wrapped?

In case it's what happens if I add a task to a queue that's already been completely processed? It will restart processing the newly added task?

**Comment by jjrv** [comment]
Yes you can always add a new task to the queue, and it starts immediately if the queue is empty or otherwise gets scheduled for later. A wrapped function should be completely transparent - you won't notice any difference in how it works other than the possible delay.

**Comment by jjrv** [comment]
To clarify, wrapping a function doesn't alter the queue or the function in any way. It only creates a new closure referencing the queue and the function. You can wrap any function with any queue at any time and any number of times you need.

Closing this, but I can reopen if you have anything to add.

**Comment by paglias** [comment]
@jjrv thanks, what I meant is this: in the README example you have

```
var queue = new TaskQueue(Promise, 3);

Promise.map(list, queue.wrap(download))); // Download 3 files at a time.
```

now Promise.map returns a Promise, my understanding if a `then` callback is attached to the Promise object it can only be called once, so what happens in this case

```
var queue = new TaskQueue(Promise, 3);

Promise.map(list, queue.wrap(download)))
  .then(function () { console.log('done') });

// In 10 seconds all the items in the queue are processed and `done` is logged by the console

// 5 seconds after the processing ends a new Task is pushed to the queue
setTimeout(function () {
    queue.add(...);
}, 15000);

// Will the `then` callback be called once again after the newly added task has been processed?
```

**Comment by jjrv** [comment]
No, "done" is not printed a second time. After the first time it's printed, no references to that function remain and it may be garbage collected.
