### ISSUE TITLE
Better typing for TaskQueue.wrap()

### ISSUE THREAD

**Issue by Mattwmaster58** [charto/cwait#9]
This is the current type of TaskQueue.wrap(): 
```wrap(func: (...args: any[]) => any, thisObject?: any): (...args: any[]) => any;```

Don't we know that `func` will be returning a promise? And don't we know that `wrap` will also return a promise?

**Comment by jjrv** [comment]
`func` is allowed to return something else, but the wrapped function will always return a promise. Correct typings would require [something like this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3db545b2/types/bluebird/index.d.ts#L542-L553) but we also want the flexibility to return Bluebird or native or some other kind of promises depending on what the queue constructor was told... I don't think representing the return type correctly is possible, casting needs to be used in the calling code.

**Comment by Mattwmaster58** [comment]
I didn't even consider the case of a different kind of promise. What are your thoughts on a convenience native method that just is synactic sugar for `new TaskQueue(Promise, num)`. Would we be able to provide more specific typings?

**Comment by jjrv** [comment]
Can you check out the current `develop` branch? I'm testing `PromiseLike` as the promise type, which would allow a properly typed `wrap` method.

**Comment by Mattwmaster58** [comment]
I tried `npm i git+https://github.com/charto/cwait#develop --save` but know the dist folder in the cwait folder in node_modules does not exist,

**Comment by jjrv** [comment]
The fix is now included in the latest release v1.1.2, does it work better?

**Comment by Mattwmaster58** [comment]
Just updated, much better. Thank you for spending the time to update this project and give this kind of attention to issues.

**Comment by Mattwmaster58** [comment]
Works flawlessly (in my simple use case). Thank you for maintaining this great project!
